[env]
SURREALDB_URL = "http://localhost:8000"
SURREALDB_USERNAME = "root"
SURREALDB_PASSWORD = "root"
SURREALDB_NAMESPACE = "development"
SURREALDB_DATABASE = "nomina"
JWT_SECRET = "GRhwVDMKj+eKNVHDdMdry9nQcmilgjP6g9UpoqeWIM5ry7mnWOGm3rHHQvdlNWwR"
ROOT_USERNAME = "root"
ROOT_PASSWORD = "v3rys3cr3t"
