use utoipa::OpenApi;

/// Aggregated OpenAPI document for the service.
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::health::check,
        crate::handlers::organization::create,
        crate::handlers::organization::list,
        crate::handlers::organization::get,
        crate::handlers::organization::update,
        crate::handlers::organization::delete,
        crate::handlers::payroll::create,
        crate::handlers::payroll::list,
        crate::handlers::payroll::get,
        crate::handlers::payroll::update,
        crate::handlers::payroll::delete,
        crate::handlers::job::create,
        crate::handlers::job::list,
        crate::handlers::job::get,
        crate::handlers::job::update,
        crate::handlers::job::delete,
        crate::handlers::division::create,
        crate::handlers::division::list,
        crate::handlers::division::get,
        crate::handlers::division::update,
        crate::handlers::division::delete,
        crate::handlers::bank::create,
        crate::handlers::bank::list,
        crate::handlers::bank::get,
        crate::handlers::bank::update,
        crate::handlers::bank::delete,
        crate::handlers::employee::create,
        crate::handlers::employee::list,
        crate::handlers::employee::get,
        crate::handlers::employee::update,
        crate::handlers::employee::delete,
    ),
    components(
        schemas(
            crate::domain::health::Health,
            crate::domain::organization::Organization,
            crate::domain::payroll::Payroll,
            crate::domain::job::Job,
            crate::domain::division::Division,
            crate::domain::bank::Bank,
            crate::domain::employee::Employee,
            crate::handlers::organization::CreateOrganizationRequest,
            crate::handlers::organization::UpdateOrganizationRequest,
            crate::handlers::organization::OrganizationResponse,
            crate::handlers::payroll::CreatePayrollRequest,
            crate::handlers::payroll::UpdatePayrollRequest,
            crate::handlers::payroll::PayrollResponse,
            crate::handlers::job::CreateJobRequest,
            crate::handlers::job::UpdateJobRequest,
            crate::handlers::job::JobResponse,
            crate::handlers::division::CreateDivisionRequest,
            crate::handlers::division::UpdateDivisionRequest,
            crate::handlers::division::DivisionResponse,
            crate::handlers::bank::CreateBankRequest,
            crate::handlers::bank::UpdateBankRequest,
            crate::handlers::bank::BankResponse,
            crate::handlers::employee::CreateEmployeeRequest,
            crate::handlers::employee::UpdateEmployeeRequest,
            crate::handlers::employee::EmployeeResponse,
        )
    ),
    tags(
        (name = "Health", description = "Service health endpoints"),
        (name = "Organizations", description = "Organization management"),
        (name = "Payrolls", description = "Payroll management"),
        (name = "Jobs", description = "Job management"),
        (name = "Divisions", description = "Division management"),
        (name = "Banks", description = "Bank management"),
        (name = "Employees", description = "Employee management"),
    )
)]
pub struct ApiDoc;
