use utoipa::OpenApi;

/// Aggregated OpenAPI document for the service.
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::auth::login,
        crate::handlers::auth::refresh,
        crate::handlers::auth::logout,
        crate::handlers::auth::me,
        crate::handlers::user::create,
        crate::handlers::user::list,
        crate::handlers::user::get,
        crate::handlers::user::update,
        crate::handlers::user::delete,
        crate::handlers::user::list_assignments,
        crate::handlers::user::assign_role,
        crate::handlers::user::revoke_role,
        crate::handlers::health::check,
        crate::handlers::organization::create,
        crate::handlers::organization::list,
        crate::handlers::organization::get,
        crate::handlers::organization::update,
        crate::handlers::organization::delete,
        crate::handlers::payroll::create,
        crate::handlers::payroll::list,
        crate::handlers::payroll::get,
        crate::handlers::payroll::update,
        crate::handlers::payroll::delete,
        crate::handlers::job::create,
        crate::handlers::job::list,
        crate::handlers::job::get,
        crate::handlers::job::update,
        crate::handlers::job::delete,
        crate::handlers::payroll_concept::create,
        crate::handlers::payroll_concept::list,
        crate::handlers::payroll_concept::get,
        crate::handlers::payroll_concept::update,
        crate::handlers::payroll_concept::delete,
        crate::handlers::division::create,
        crate::handlers::division::list,
        crate::handlers::division::get,
        crate::handlers::division::update,
        crate::handlers::division::delete,
        crate::handlers::bank::create,
        crate::handlers::bank::list,
        crate::handlers::bank::get,
        crate::handlers::bank::update,
        crate::handlers::bank::delete,
        crate::handlers::employee::create,
        crate::handlers::employee::list,
        crate::handlers::employee::get,
        crate::handlers::employee::update,
        crate::handlers::employee::delete,
        crate::handlers::employee_payroll_concept::create,
        crate::handlers::employee_payroll_concept::list,
        crate::handlers::employee_payroll_concept::get,
        crate::handlers::employee_payroll_concept::update,
        crate::handlers::employee_payroll_concept::delete,
        crate::handlers::payroll_concept_definition::create,
        crate::handlers::payroll_concept_definition::get,
        crate::handlers::payroll_concept_definition::update,
        crate::handlers::payroll_concept_definition::delete,
        crate::handlers::payroll_history::create,
        crate::handlers::payroll_history::list,
        crate::handlers::payroll_history::get,
        crate::handlers::payroll_history::update,
        crate::handlers::payroll_history::delete,
        crate::handlers::payroll_history_detail::create,
        crate::handlers::payroll_history_detail::list,
        crate::handlers::payroll_history_detail::get,
        crate::handlers::payroll_history_detail::delete,
        crate::handlers::payroll_calculator::calculate,
        crate::handlers::payroll_calculator::clean,
        crate::handlers::payroll_calculator::recalculate,
    ),
    components(
        schemas(
            crate::domain::user::User,
            crate::domain::role::Role,
            crate::domain::permission::Permission,
            crate::domain::user_role_assignment::UserRoleAssignment,
            crate::handlers::auth::LoginRequest,
            crate::handlers::auth::LoginResponse,
            crate::handlers::auth::RefreshResponse,
            crate::handlers::auth::UserPayload,
            crate::handlers::user::CreateUserRequest,
            crate::handlers::user::UpdateUserRequest,
            crate::handlers::user::UserResponse,
            crate::handlers::user::AssignRoleRequest,
            crate::handlers::user::UserRoleAssignmentResponse,
            crate::domain::health::Health,
            crate::domain::organization::Organization,
            crate::domain::payroll::Payroll,
            crate::domain::job::Job,
            crate::domain::payroll_concept::PayrollConcept,
            crate::domain::payroll_concept::PayrollConceptType,
            crate::domain::payroll_concept::PayrollConceptScope,
            crate::domain::payroll_concept::PayrollConceptPeriod,
            crate::domain::payroll_concept_definition::PayrollConceptDefinition,
            crate::domain::division::Division,
            crate::domain::bank::Bank,
            crate::domain::employee::Employee,
            crate::domain::employee_payroll_concept::EmployeePayrollConcept,
            crate::domain::payroll_history::PayrollHistory,
            crate::domain::payroll_history::PayrollHistoryStatus,
            crate::domain::payroll_history_detail::PayrollHistoryDetail,
            crate::handlers::organization::CreateOrganizationRequest,
            crate::handlers::organization::UpdateOrganizationRequest,
            crate::handlers::organization::OrganizationResponse,
            crate::handlers::payroll::CreatePayrollRequest,
            crate::handlers::payroll::UpdatePayrollRequest,
            crate::handlers::payroll::PayrollResponse,
            crate::handlers::job::CreateJobRequest,
            crate::handlers::job::UpdateJobRequest,
            crate::handlers::job::JobResponse,
            crate::handlers::payroll_concept::CreatePayrollConceptRequest,
            crate::handlers::payroll_concept::UpdatePayrollConceptRequest,
            crate::handlers::payroll_concept::PayrollConceptResponse,
            crate::handlers::division::CreateDivisionRequest,
            crate::handlers::division::UpdateDivisionRequest,
            crate::handlers::division::DivisionResponse,
            crate::handlers::bank::CreateBankRequest,
            crate::handlers::bank::UpdateBankRequest,
            crate::handlers::bank::BankResponse,
            crate::handlers::employee::CreateEmployeeRequest,
            crate::handlers::employee::UpdateEmployeeRequest,
            crate::handlers::employee::EmployeeResponse,
            crate::handlers::employee_payroll_concept::CreateEmployeePayrollConceptRequest,
            crate::handlers::employee_payroll_concept::UpdateEmployeePayrollConceptRequest,
            crate::handlers::employee_payroll_concept::EmployeePayrollConceptResponse,
            crate::handlers::payroll_concept_definition::CreatePayrollConceptDefinitionRequest,
            crate::handlers::payroll_concept_definition::UpdatePayrollConceptDefinitionRequest,
            crate::handlers::payroll_concept_definition::PayrollConceptDefinitionResponse,
            crate::handlers::payroll_history::CreatePayrollHistoryRequest,
            crate::handlers::payroll_history::UpdatePayrollHistoryRequest,
            crate::handlers::payroll_history::PayrollHistoryResponse,
            crate::handlers::payroll_history_detail::CreatePayrollHistoryDetailRequest,
            crate::handlers::payroll_history_detail::PayrollHistoryDetailResponse,
            crate::handlers::payroll_calculator::CalculationResponse,
            crate::handlers::payroll_calculator::CleanResponse,
        )
    ),
    tags(
        (name = "Auth", description = "Authentication endpoints"),
        (name = "Users", description = "User management"),
        (name = "Health", description = "Service health endpoints"),
        (name = "Organizations", description = "Organization management"),
        (name = "Payrolls", description = "Payroll management"),
        (name = "Payroll Concepts", description = "Payroll concept management"),
        (name = "Jobs", description = "Job management"),
        (name = "Divisions", description = "Division management"),
        (name = "Banks", description = "Bank management"),
        (name = "Employees", description = "Employee management"),
        (name = "Employee Payroll Concepts", description = "Employee-specific payroll concept assignments"),
        (name = "Payroll History", description = "Payroll history tracking"),
        (name = "Payroll History Details", description = "Payroll history detail records"),
        (name = "Payroll Calculator", description = "Payroll calculation and recalculation operations"),
    )
)]
pub struct ApiDoc;
